version: '3.8'
services:
  project:
    build:
      context: Backend/
    volumes:
      - data:/code
    env_file:
      - .env
    ports:
      - 8000:8000

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/$USER/Desktop/test