version: '3.8'

services:
  ngnix:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./Frontend:/usr/share/nginx/html
      - ./Frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - backend_network

  web:
    build:
      context: ./Backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - backend_network

  # postgresql container
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    networks:
      - backend_network

  # has to be removed in production...
  db-admin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin/
    env_file:
      - ./.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@example.com # user name 
      - PGADMIN_DEFAULT_PASSWORD=${SQL_PASSWORD} # pass django
    ports:
      - 8080:8080
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
