version: '3.8'

#DEVELOPMENT ONLY *remove this file before deployment*

services:
   ngnix:
    container_name: Frontend
    build:
      context: ./Frontend
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./Frontend/srcs:/usr/share/nginx/html
      - ./Frontend/srcs/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - backend

  app:
    build:
      context: ./Backend
    volumes:
      - ./Backend:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    container_name: postgres
    build:
      context: ./Postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: on-failure
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    networks:
      - backend


  db-admin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin/
    env_file:
      - ./.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@example.com # user name 
      - PGADMIN_DEFAULT_PASSWORD=${SQL_PASSWORD} # pass django
    ports:
      - 8080:8080
    networks:
      - backend
networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
