services:
  - type: web
    name: ngnix
    runtime: docker
    dockerfilePath: ./Frontend/Dockerfile  # Path to the Dockerfile for the ngnix service
    ports:
      - 80
    dependsOn:
      - app

  - type: web
    name: app
    runtime: docker
    dockerfilePath: ./Backend/Dockerfile  # Path to the Dockerfile for the app service
    ports:
      - 8000
    dependsOn:
      - postgres

  - type: web
    name: db-admin
    runtime: docker
    image: dpage/pgadmin4
    ports:
      - 8080
    dependsOn:
      - postgres

  - type: postgres
    name: postgres
    runtime: docker
    dockerfilePath: ./Postgres/Dockerfile  # Path to the Dockerfile for the postgres service
